language: csharp
dotnet: 2.1.4
mono: none

matrix:
  include:
    - os: osx
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9

script:
  # If we're on Linux, print out the dynamic linker configuration for the quantum
  # runtime to see what dependencies we're missing.
  - dotnet restore QsharpLibraries.sln
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ldd `find ~/.nuget/packages -name "Microsoft.Quantum.Simulator.Runtime.dll"`; fi
  - dotnet build QsharpLibraries.sln
  - dotnet test Samples/UnitTesting
  - travis_wait dotnet test LibraryTests

